### PR TITLE
🔧 Use test scopes to enforce testing styles

### PR DESCRIPTION
**Pull request by daividssilverio**
## Summary
This is a version of the TestStore that enforces the testing style and hides direct store access to exhaustive configurations.

## Technical considerations
Some 🧹 and documentations might need to adjusted to make up for the changes.

## Tests
Properly adapted.

## Review pointers
Try to write some tests, note that we are now always one explicit kind of test scope (exhaustive/non-exhaustive) with different actions that can be used.

Note that exhaustive is the default, and `finish()` is enforced on every test
On non exhaustive tests, the user has manually await for effects and an extra assertion method is provided for asserting the state as necessary in the end.

### CODE REVIEW

**Review by semanticer — CHANGES_REQUESTED** [review]
I like where this is going but it got me thinking... I think we should go even further with this stateless thing and forget about TCA's implementation. 
The fact that `TestStore` is maintaining `var exhaustivity: Exhaustivity` and thus has to support both cases and users need to think about TestStore's internal state is making everything more confusing and the implementation more complex. I think we should also move closer to our other testing APIs such as: 

```kotlin
reducer.testReduce(
    initialState = initialState,
    action = TodoAction.IsCompleteChanged(true),
) { state, effect ->
    state shouldBe initialState.copy(isComplete = true)
    effect shouldBe NoEffect
}
```

we can do something very similar for teststore testing, something like: 

```kotlin
reducer.testExhaustively(
    initialState = initialState,
    config = config
) {
    send(...)
    receive(...)
}
```

config can contain testCoroutineScope, timeout etc and can be defined only once passed to every `testExhaustively` or `testNonExhaustively` instance. 

Side note: not sure if `testExhaustively` or `exhaustiveTest` is better. 

I wouldn't also bother supporting mixing non exhaustive test block within exhaustive blocks and vice versa.

**Review by semanticer — CHANGES_REQUESTED** [review]
This looks and works well, but we're still letting users shoot themselves in the foot. Let me show you what I mean:

```kotlin 
// should we let users create TestStore instances directly when there is not much they can do with it anyway?
val exhaustiveTestStore = TestStore( { initialState }, { todosReducer }, ExhaustiveTestConfig(dispatcherProvider, testCoroutineScope))
// creating NonExhaustiveTestStoreScope with an exhaustive test store shouldn't be possible
val scope = NonExhaustiveTestStoreScope(exhaustiveTestStore)
// running receive outside of a test block from NonExhaustiveTestStoreScope with exhaustive test store 🙌
scope.receive(TodosAction.AddTodoButtonTapped) {
    it.copy(todos = it.todos + TodoState(UUID(0, 1), "", false))
}
```

We need to decide if there is a valid reason to let users do the testing outside of the `test { }` block, if yes, then we need to support it better and make things like the one I did above impossible. If not (and I'd say we shouldn't) we need to make this thing impossible altogether. This can be done simply by making TestStore and TestStoreScopes constructors internal or by doing even bigger structural changes - let me draft something small to explain what I mean.

**Comment by semanticer** [comment]
@daividssilverio take a look at https://github.com/toggl/komposable-architecture/commit/da684cfb79f6f4783675438f123ade3abd6598dd

The idea there was to: 
1) Make TestStore's exhaustivity immutable but still allow for temporary exhaustivity changes. My solution doesn't change that much technically, but I'm trying to make a clear distinction between original config exhaustivity and the one we use for one shot actions only. 
2) Hide scope implementations from the user behind interfaces
3) Add some private and internal modifiers

I also think we should move the docs from TestStore internal methods to interface methods. Users shouldn't even know about the TestStore's existence. 

wdyt?

**Comment by daividssilverio** [comment]
I see @semanticer , I agree with most of what you said.

> We need to decide if there is a valid reason to let users do the testing outside of the test { } block, if yes, then we need to support it better and make things like the one I did above impossible. If not (and I'd say we shouldn't) we need to make this thing impossible altogether.

Your opinion didn't came out clear to me. Are you favor of hiding the TestStore altogether and only expose the scopes through extensions?

> Make TestStore's exhaustivity immutable but still allow for temporary exhaustivity changes. My solution doesn't change that much technically, but I'm trying to make a clear distinction between original config exhaustivity and the one we use for one shot actions only.

If we make test store not directly instantiable, it's enough to make the exhaustivity private, isn't it? It would be just implementation detail and that `temp` thing you've suggested would be overkill. Or are you trying to prevent future implementation mistakes or something like that?

**Comment by semanticer** [comment]
> Your opinion didn't came out clear to me. Are you favor of hiding the TestStore altogether and only expose the scopes through extensions?

Yes, I'm for making this foolproof and as restricted as possible to reduce complexity of the API. 

> If we make test store not directly instantiable, it's enough to make the exhaustivity private, isn't it? It would be just implementation detail and that temp thing you've suggested would be overkill. Or are you trying to prevent future implementation mistakes or something like that?

You're right, my overkill suggestion doesn't change anything user-facing, and this whole thing is indeed just an implementation detail. My aim was to make it more explicit internally as well, but I might have gone overboard. Feel free to ignore this if you don't like it.

**Review by semanticer — APPROVED** [review]
I love how you separated things further. Let's merge this finally 🙌

**Pull request merged**
