### PR TITLE
🏗️ Make Effects functional interfaces

### PR DESCRIPTION
**Pull request by heytherewill**
## Summary
This updates the interface definition of Effect to mark it as a functional interface (SAM)

## Technical considerations

It wasn't possible to have a SAM whose only method was a suspending fun in the version of Kotlin that we were using when building the library. Newer version of Kotlin allow it (hence why I bumped it)

## Tests
No behavioral changes were made. It makes sense for the classes inside the library to be properly inherited, but there are use cases for users to have small, anonymous effects (similar to how Reducers can be full blown classes or not)

### CODE REVIEW

**Review by daividssilverio — APPROVED** [review]
Seems like a nice to have. Tests are looking fine.

**Comment by daividssilverio** [comment]
It would be nice if you could give an example (actual code) of the usages you've thought about when requesting for this change.

**Comment by heytherewill** [comment]
My thinking is that things like simple effect factories can be like:

```
class SimpleEffectFactory @Inject constructor(
    private val dependencyA: DependencyA,
    private val dependencyB: DependencyB
) {

    fun createFor(parameter: String) = Effect {
        dependencyA.foo(dependencyB.bar, parameter)
        null
    }
}
```

Instead of
```
class SimpleEffectFactory @Inject constructor(
    private val dependencyA: DependencyA,
    private val dependencyB: DependencyB
) {

    fun createFor(parameter: String) = object : Effect {
        override suspend fun execute(): Action? {
            dependencyA.foo(dependencyB.bar, parameter)
            return null
        }
    }
}
```

Furthermore, in simple reducers (like one that only provides logging), you can have a single anonymous effect where the user can perform side effects galore with a much more compact syntax

**Review by semanticer — APPROVED** [review]
Not sure why we haven't had this before 🤷

**Pull request merged**
